### ISSUE TITLE
OpenCV error

### ISSUE THREAD

**Issue by xMutzelx** [wg-perception/tod#14]
Hello, 
I try to use TOD but I get the following errors:

```
rosrun object_recognition_core detection -c `rospack find object_recognition_tod`/conf/detection.ros.ork
[ INFO] [1465555596.833485350]: Initialized ROS. node_name: /object_recognition_server
[ INFO] [1465555597.097880674]: System already initialized. node_name: /object_recognition_server
[ INFO] [1465555597.434697487]: System already initialized. node_name: /object_recognition_server
[ INFO] [1465555597.442048043]: Subscribed to topic:/camera/depth_registered/camera_info [queue_size: 1][tcp_nodelay: 0]
[ INFO] [1465555597.446187652]: Subscribed to topic:/camera/rgb/camera_info [queue_size: 1][tcp_nodelay: 0]
[ INFO] [1465555597.450510176]: Subscribed to topic:/camera/rgb/image_color [queue_size: 1][tcp_nodelay: 0]
[ INFO] [1465555597.454726395]: Subscribed to topic:/camera/depth_registered/image_raw [queue_size: 1][tcp_nodelay: 0]
[ INFO] [1465555598.069948051]: publishing to topic:/recognized_object_array
Loading models. This may take some time...
Loading models. This may take some time...
Loading model for object id: 544ac4d13f955e6ebb22518b3f002734
span: 0.282535 meters
Loading model for object id: 544ac4d13f955e6ebb22518b3f0001f1
OpenCV Error: Assertion failed (func != 0) in transpose, file /build/buildd/opencv-2.4.8+dfsg1/modules/core/src/matrix.cpp, line 2023
Traceback (most recent call last):
  File "/home/marcel/catkin_ws/src/object_recognition_core/apps/detection", line 24, in <module>
    run_plasm(args, plasm)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/ecto/opts.py", line 85, in run_plasm
    sched.execute(options.niter)
ecto.CellException:            exception_type  CellException
[cell_name] = pipeline1

[cell_type] = ecto::py::BlackBox

[function_name] = process_with_only_these_inputs

[type] = std::runtime_error

[what] =            exception_type  CellException
[cell_name] = Matcher

[function_name] = process_with_only_these_inputs

[type] = cv::Exception

[what] = /build/buildd/opencv-2.4.8+dfsg1/modules/core/src/matrix.cpp:2023: error: (-215) func != 0 in function transpose


[when] = While triggering param change callbacks
```

Last output before error: "Loading model for object id: 544ac4d13f955e6ebb22518b3f0001f1"
This is the standard coke.stl. Without the coke it is working, pretty bad but it is working.

This is my TOD detection.ros.ork file:

```
#source1:
#  type: 'OpenNI'
#  module: 'object_recognition_core.io.source'
#  parameters:
#    image_mode: 'SXGA_RES'
#    depth_mode: 'VGA_RES'
#    image_fps: 'FPS_15'
#    depth_fps: 'FPS_30'

#Use this instead to receive images via ROS
source1:
  type: RosKinect
  module: 'object_recognition_ros.io'
  parameters:
    rgb_frame_id: 'camera_rgb_optical_frame'
    rgb_camera_info: '/camera/rgb/camera_info'
    rgb_image_topic: '/camera/rgb/image_color'
    depth_camera_info: '/camera/depth_registered/camera_info'
    depth_image_topic: '/camera/depth_registered/image_raw'


sink1:
  type: 'Publisher'
  module: 'object_recognition_ros.io'
  parameters:
    visualize: true
    object_ids: 'all'

sink2:
  type: Publisher
  module: 'object_recognition_ros.io'
  inputs: [source1]

voter1:
  type: 'Aggregator'
  module: 'object_recognition_core.io'
  outputs: [sink1]

pipeline1:
  type: 'TodDetector'
  module: 'object_recognition_tod'
  inputs: [source1]
  outputs: [voter1, sink2]
  parameters:
    object_ids: "all"
    feature:
      type: ORB
      module: ecto_opencv.features2d
      n_features: 1000
      n_levels: 3
      scale_factor: 1.2
    descriptor:
      type: ORB
      module: ecto_opencv.features2d
    search: 
      type: LSH
      module: ecto_opencv.features2d
      key_size: 24
      multi_probe_level: 2
      n_tables: 8
      radius: 55
      ratio: 0.8
    n_ransac_iterations: 1000
    min_inliers: 6
    sensor_error: 0.01
    db:
      type: CouchDB
      root: http://localhost:5984
      collection: object_recognition
```

I am using the Kinect together with openni_launch. I am working on Ubuntu 14.04 and on ROS indigo.
I am using GLUT and not OSMesa [see here](https://github.com/wg-perception/ork_renderer/pull/9/files). 
I also changed some versions of packages:

```
1. visualization: f072ccf
2. tod: 0.5.5
3. transparent: 75d7663
4. reconstruct: 8adb948
5. core: fb3b3df
6. capture: 0.3.1
7. renderer: 3af6195
8. tabletop: 7d49e3e
9. linemod: 3b8ddca
```

Linemod and Tabletop are working like a charm. I have 3 objects in my database. 
Thank you very much for your help, I really appreciate it.

**Comment by vrabaud** [comment]
Why did you close that bug ?

**Comment by xMutzelx** [comment]
I answered my own issue in my question. I wrote that it is working but not with the coke.stl. Afterwards I realized, that the coke.stl doesn't have a texture and TOD needs a texture. That is the reason for my error message. Sorry for this useless issue.
